# Generated by Django 4.2.27 on 2025-12-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='video_caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='performance',
            name='video_file',
            field=models.FileField(blank=True, help_text='Или загрузите видеофайл', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='performance',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео YouTube/Vimeo (если есть)', null=True),
        ),
    ]
