# Generated by Django 4.2.27 on 2025-12-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_performance_video_caption_performance_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='location',
        ),
    ]
