# Generated by Django 4.2.27 on 2025-12-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_remove_performance_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='video_caption',
        ),
        migrations.AlterField(
            model_name='performance',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео YouTube/Vimeo', null=True),
        ),
    ]
